ALTER TABLE dbo.t_purchases 
ADD COLUMN user_id bigint;

ALTER TABLE dbo.t_purchases 
ADD CONSTRAINT FK_purch_user_id FOREIGN KEY (user_id)
REFERENCES dbo.t_users (user_id);


create table dbo.t_clients_users(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    client_id bigint,
    user_id bigint,
    change_dttm timestamptz not null default(current_timestamp),
    CONSTRAINT FK_client_id FOREIGN KEY (client_id)
        REFERENCES dbo.t_clients (client_id),
    CONSTRAINT FK_user_id FOREIGN KEY (user_id)
    REFERENCES dbo.t_users (user_id),
    PRIMARY KEY (id)
);