
CREATE SCHEMA IF NOT EXISTS dbo;
create table dbo.t_aircraft_models(
    aircraft_model_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    aircraft_iata_code varchar(100) NOT NULL,
    aircraft_icaic_code varchar(100) NOT NULL,
    aircraft_model_name varchar(100) NOT NULL,
    aircraft_model_manufacturer varchar(100) NOT NULL,
    aircraft_model_wing_type varchar(100) NOT NULL,
    aircraft_model_type varchar(100) NOT NULL,
    economy_class_flg char(1),
    pr_economy_class_flg char(1),
    business_class_flg char(1),
    first_class_flg char(1),
    change_dttm timestamptz not null default(current_timestamp),
    CONSTRAINT CK_economy_class_flg CHECK (economy_class_flg IN ('Y','N')),
    CONSTRAINT CK_pr_economy_class_flg CHECK (pr_economy_class_flg IN ('Y','N')),
    CONSTRAINT CK_business_class_flg CHECK (business_class_flg IN ('Y','N')),
    CONSTRAINT CK_first_class_flg CHECK (first_class_flg IN ('Y','N')),
    PRIMARY KEY (aircraft_model_id)
);




create table dbo.t_countries(
    country_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    country_code varchar(100) NOT NULL UNIQUE,
    country_name varchar(100) NOT NULL UNIQUE,
    country_continent varchar(100) NOT NULL,
    country_wikipedia_link varchar(1000),
    change_dttm timestamptz not null default(current_timestamp),
    PRIMARY KEY (country_id)
);






create table dbo.t_airlines(
    airline_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    airline_iata varchar(100) NOT NULL,
    airline_icao varchar(100) NOT NULL,
    airline_country_id int,
    airline_active_flg char(1),
    change_dttm timestamptz not null default(current_timestamp),
    CONSTRAINT CK_active_flg CHECK (airline_active_flg IN ('Y','N')),
    CONSTRAINT FK_country FOREIGN KEY (airline_country_id)
        REFERENCES dbo.t_countries (country_id),
    PRIMARY KEY (airline_id)
);





create table dbo.t_airports(
    airport_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    airport_type varchar(30),
    airport_name varchar(100) NOT NULL UNIQUE,
    airport_iso_country_id int NOT NULL,
    airport_iso_region varchar(100) NOT NULL,
    airport_municipality varchar(100) NOT NULL,
    airport_iata_code varchar(100) NOT NULL UNIQUE,
    airport_home_link varchar(1000),
    visa_flg char(1),
    quarantine_flg char(1),
    covid_test_flg char(1),
    lockdown_flg char(1),
    change_dttm timestamptz not null default(current_timestamp),
    CONSTRAINT CK_visa_flg CHECK (visa_flg IN ('Y','N')),
    CONSTRAINT CK_quarantine_flg CHECK (quarantine_flg IN ('Y','N')),
    CONSTRAINT CK_covid_test_flg CHECK (covid_test_flg IN ('Y','N')),
    CONSTRAINT CK_lockdown_flg CHECK (lockdown_flg IN ('Y','N')),
    CONSTRAINT CK_airport_type CHECK (airport_type IN ('balloonport',
                                                        'closed',
                                                        'heliport',
                                                        'large_airport',
                                                        'medium_airport',
                                                        'medium_airport',
                                                        'small_airport')),
    CONSTRAINT FK_iso_country FOREIGN KEY (airport_iso_country_id)
        REFERENCES dbo.t_countries (country_id),
    PRIMARY KEY (airport_id)
);




create table dbo.t_flights(
    flight_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    flight_name varchar(100) NOT NULL,
    airline_id int,
    ticket_num_economy_class int DEFAULT 0,
    ticket_num_pr_economy_class int DEFAULT 0,
    ticket_num_business_class int DEFAULT 0,
    ticket_num_first_class int DEFAULT 0,
    cost_economy_class_rub decimal(10,2),
    cost_pr_economy_class_rub decimal(10,2),
    cost_business_class_rub decimal(10,2),
    cost_first_class_rub decimal(10,2),
    aircraft_model_id int,
    departure_airport_id int,
    landing_airport_id int,
    departure_time timestamptz not null,
    landing_time timestamptz not null,
    max_luggage_weight_kg decimal(10,4),
    cost_luggage_weight_rub decimal(10,2),
    max_hand_luggage_weight_kg decimal(10,4),
    cost_hand_luggage_weight_rub decimal(10,2),
    wifi_flg char(1),
    food_flg char(1),
    usb_flg char(1),
    change_dttm timestamptz not null default(current_timestamp),
    CONSTRAINT CK_wifi_flg CHECK (wifi_flg IN ('Y','N')),
    CONSTRAINT CK_food_flg CHECK (food_flg IN ('Y','N')),
    CONSTRAINT CK_usb_flg CHECK (usb_flg IN ('Y','N')),
    CONSTRAINT FK_aircraft_model_id FOREIGN KEY (aircraft_model_id)
        REFERENCES dbo.t_aircraft_models (aircraft_model_id),
    CONSTRAINT FK_departure_airport_id FOREIGN KEY (departure_airport_id)
        REFERENCES dbo.t_airports (airport_id),
    CONSTRAINT FK_landing_airport_id FOREIGN KEY (landing_airport_id)
        REFERENCES dbo.t_airports (airport_id),
    CONSTRAINT FK_airline_id FOREIGN KEY (airline_id)
        REFERENCES dbo.t_airlines (airline_id),
    PRIMARY KEY (flight_id)
);




create table dbo.t_users(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_email varchar(255) NOT NULL,
    user_password varchar(255) NOT NULL,
    user_first_name varchar(255) NOT NULL,
    user_last_name varchar(255) NOT NULL,
    user_middle_name varchar(255),
    user_phone_number varchar(255) NOT NULL,
    birth_date date NOT NULL,
    user_country_id int,
    passport_number varchar(255),
    passport_series varchar(255),
    passport_address varchar(1000),
    living_address varchar(1000),
    create_dttm timestamptz not null default(current_timestamp),
    change_dttm timestamptz not null default(current_timestamp),
    CONSTRAINT FK_t_countries FOREIGN KEY (user_country_id)
        REFERENCES dbo.t_countries (country_id),
    PRIMARY KEY (user_id)
);

create table dbo.t_admins(
    admin_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    admin_email varchar(255) NOT NULL,
    admin_password varchar(255) NOT NULL,
    privileges_level char(1) NOT NULL,
    change_dttm timestamptz not null default(current_timestamp),
    PRIMARY KEY (admin_id)
);



create table dbo.t_purchases(
    purchase_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    flight_id bigint,
    cost_rub_amt decimal(12,2) NOT NULL,
    class_flg varchar(100) NOT NULL,
    food_flg char(1) NOT NULL,
    purchase_dttm timestamptz not null default(current_timestamp),
    change_dttm timestamptz not null default(current_timestamp),
    CONSTRAINT CK_purch_food_flg CHECK (food_flg IN ('Y','N')),
    CONSTRAINT CK_purch_class_flg CHECK (class_flg IN ('economy','pr_economy', 'business', 'first')),
    CONSTRAINT FK_purch_user_id FOREIGN KEY (user_id)
        REFERENCES dbo.t_users (user_id),
    CONSTRAINT FK_purch_flight_id FOREIGN KEY (flight_id)
        REFERENCES dbo.t_flights (flight_id),
    PRIMARY KEY (purchase_id)
);